import "@haxtheweb/course-design/lib/learning-component.js";
import "@haxtheweb/grid-plate/grid-plate.js";
import "@haxtheweb/simple-cta/simple-cta.js";
import "@haxtheweb/multiple-choice/multiple-choice.js"; import "@haxtheweb/tagging-question/tagging-question.js";
import "@haxtheweb/rpg-character/rpg-character.js";
import "@haxtheweb/course-design/lib/activity-box.js";
import "@haxtheweb/vocab-term/vocab-term.js";
import "@haxtheweb/media-image/media-image.js";
import "@haxtheweb/citation-element/citation-element.js";
import "@haxtheweb/self-check/self-check.js";
import '@haxtheweb/mark-the-words/mark-the-words.js';

// import "@haxtheweb/page-section/page-section.js";
// import "@haxtheweb/page-break/page-break.js";
// import "@haxtheweb/page-break/lib/page-anchor.js";
// import "@haxtheweb/spotify-embed/spotify-embed.js";
// import "@haxtheweb/inline-audio/inline-audio.js";
// import "@haxtheweb/course-model/course-model.js";
// import "@haxtheweb/audio-player/audio-player.js";
import "@haxtheweb/simple-fields/lib/simple-tags.js";
import "@haxtheweb/stop-note/stop-note.js";
// import "@haxtheweb/inline-audio/inline-audio.js";
// import "@haxtheweb/moar-sarcasm/moar-sarcasm.js";
import "@haxtheweb/flash-card/flash-card.js";
// import "@haxtheweb/video-player/video-player.js";
// import "@haxtheweb/course-design/lib/block-quote.js";
// import "@haxtheweb/a11y-collapse/a11y-collapse.js";
// import "@haxtheweb/accent-card/accent-card.js";
// import "@haxtheweb/a11y-gif-player/a11y-gif-player.js";
// import "@haxtheweb/code-sample/code-sample.js";
// import "@haxtheweb/image-compare-slider/image-compare-slider.js";
// import "@haxtheweb/meme-maker/meme-maker.js";
// import "@haxtheweb/lrndesign-timeline/lrndesign-timeline.js";
// import "@haxtheweb/person-testimonial/person-testimonial.j";
// import "@haxtheweb/h5p-element/h5p-element.js";
// import "@haxtheweb/wikipedia-query/wikipedia-query.js";
// import "@haxtheweb/place-holder/place-holder.js";
// import "@haxtheweb/q-r/q-r.js";
// import "@haxtheweb/date-card/date-card.js";

import { SchemaBehaviors } from "@haxtheweb/schema-behaviors/schema-behaviors.js";
import { lazyImageLoader } from "@haxtheweb/lazy-image-helpers/lazy-image-helpers.js";
import { I18NMixin } from "@haxtheweb/i18n-manager/lib/I18NMixin.js";
import "@haxtheweb/simple-icon/simple-icon.js";
import "@haxtheweb/simple-icon/lib/simple-icons.js";
import "@haxtheweb/simple-icon/lib/simple-icon-button.js";